services:
  api:
    # Mount repo into container so that edits are seen within container
    volumes:
      - .:/app

    # Override command for dev reload
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"